
    create table customer (
       ID bigint generated by default as identity,
        comments varchar(255),
        name varchar(255),
        registered timestamp,
        primary key (ID)
    );
